name: On Pull Request

on:
  pull_request:
    branches:
      - master
      - development
      - release/*
    paths-ignore:
      - '.gitignore'
      - '.gitattributes'
      - 'LICENSE'
      - '**/*.md'

jobs:
  test:
    uses: ./.github/workflows/test.yml
    if: |
        github.event.pull_request.changes != null &&
        (
          contains(github.event.pull_request.changes.*.filename, '.csproj') ||
          contains(github.event.pull_request.changes.*.filename, '.cs')
        )
  pack:
    needs: [test]
    uses: ./.github/workflows/pack.yml
